# Generated by Django 6.0.3 on 2026-03-29 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('allows_custom_answer', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['quiz', 'order'], name='quiz_questi_quiz_id_f13328_idx')],
                'unique_together': {('quiz', 'order')},
            },
        ),
    ]
