# Generated by Django 6.0.3 on 2026-03-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='custom_answer',
        ),
    ]
