# Generated by Django 6.0.3 on 2026-03-29 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_session_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='allows_custom_answer',
        ),
    ]
